# fly.toml app configuration file generated for oceanlandstatistic-backend on 2023-05-01T19:19:59+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "oceanlandstatistic-backend"
primary_region = "cdg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
